security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Codegen\UserBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: CodegenUserBundle:User }
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
                
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
            
        codegen_firewall:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: bssplash
            logout:
                path:   /logout
                target: /login
                
            #usergrid:
               #provider: entity
               #usergrid_path: /usergrid
               #check_path: /login_check
               #use_forward: true
            
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/secured/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/secured$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usergrid, roles: IS_AUTHENTICATED_ANONYMOUSLY }