<?php

namespace Codegen\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    
        public function getAssocUsers($roleId) {

        $query = $this->getEntityManager()
                  ->createQuery('
            SELECT u.id,u.username,u.firstname,u.lastname,u.image,u.email,u.password,u.isActive
          
                FROM CodegenUserBundle:User u
                  
                WHERE u.role=' . $roleId
        );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
